spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practica4?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: lolosa123
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removedAbandoned: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    thymeleaf:
      cache: false